### ISSUE TITLE
Need to add timezone configuration to management menu

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#173]
Many raspberry pi users can't understand, how to change a time. Now it's very difficult, you need go to management->firmare update->press update to latest, in webif window -> Advanced->Setup->Timezone:
Europe/Moscow.

Please add a list with all timezones to management menu.

**Comment by Toffi32** [comment]
I have to join the issue. because I had also problems setting the correct time. I did not find anything about that in the documentation and had to search the web.
I tried some inputs and because nothing happend (Attention: You have to reboot before the timezone is set accordingly!) I entered "localtime" in  webif window -> Advanced->Setup->Timezone, which lead to an circular reference in the OS:
etc/localtime -> /usr/share/zoneinfo/localtime
/usr/share/zoneinfo/localtime -> etc/localtime
only via shell I was able to fix that by setting
rm /etc/localtime 
ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime 
It is very frustrating to spend time on such "small" things ...
