### ISSUE TITLE
What is happening with App rating?

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#192]
I can't find the the place to submit a rating for an App anymore. Am I missing something? 
Has that been deliberatelu removed? If so, than the ordering of Apps by their **rating** should also be removed from Smarthome.

**Comment by ronie-z-wave** [comment]
Did you also check Online Apps? Its feature related to the online apps so it should work there. Adding also it to downloaded apps, could be an enhancement for next changes.

**Comment by pz1** [comment]
> Did you also check Online Apps?
Yes, that's where I checked it with my v2.2.4-rc20 installations. It did work there in the past IIRC. 
Also no luck with downloaded apps.

**Comment by ronie-z-wave** [comment]
Ok, we've checked it on some RPi's with v2.2.4-rc20 with no problems. Rating and filter is working on our side. 

Only to clearify how it should be:

* ratings are only shown in online-app tab
* rating of an app is visible in overview (not clickable) and in app description (clickable)
* the average should in-/decrease count of stars if it is enough to change the rating
* if you've already rated an app an error mesage should be shown

Could you send us some screens maybe with network console output from browser (F12)? 
We didn't touch this since some month so its strange that you couldn't see it anymore ...

**Comment by pz1** [comment]
App description example: (happens to I think all Apps on FF and Chrome)
![zd2012](https://cloud.githubusercontent.com/assets/7747627/19469002/b8c29d14-9519-11e6-8033-397d52d3cba6.PNG)
What should I be looking for under F12 /network? If I scroll down these lists there is nothing that makes sense to me:
![f12](https://cloud.githubusercontent.com/assets/7747627/19469561/20dd3920-951c-11e6-950e-97152c09a26f.PNG)

**Comment by ronie-z-wave** [comment]
Ah, ok think we get it. The remote id of your box is used to check for rating feature. Unfortuantely it is checked in RemoteAccess app instead of using the api for this - thats what we've missed to change, so it's now on our todo list.

Please check if App RemoteAccess is active.This should be solve this issue meanwhile.

**Comment by pz1** [comment]
> Please check if App RemoteAccess is active.This should be solve this issue meanwhile

It is inactive. So that explains the situation.

I'll see it fixed in a upcoming release. Closing this issue
