### ISSUE TITLE
RGB no longer working in rc43

### ISSUE THREAD

**Issue by Quax1507** [Z-Wave-Me/zwave-smarthome#20]
RGB app is no longer working in rc43

**Comment by ronie-z-wave** [comment]
Please give some more information about what exactly is not working. If initailization fails or error is shown in log please add a screen of your z-way-server.log.

**Comment by Quax1507** [comment]
I am able to turn on/off the device with RGB app but I am unable to change the colour. I found nothing in the log when changing colour and nothing happens.

**Comment by ronie-z-wave** [comment]
Ok. which device are you using?

**Comment by Quax1507** [comment]
It is a Fibaro RGBW Controller FGRGBWM-441

**Comment by ronie-z-wave** [comment]
does this work before with Fibaro RGBW? I've tested this with Fibaro RGBW Controller FGRGBW-101. And as I can see RGB module seems to be for use with three dimmers (one for each color R/G/B) ... in my case there is only one switchMultiLevel Class from Fibaro RGBW and the RGB module cannot handle this I think ... but of course I did not used/tested this before so stay free to correct me if I'm wrong

**Comment by Quax1507** [comment]
Sorry, I have a FGRGB-101, too! But now it is suddenly discovered as FGRGBWM-441. 
I cannot find a device description for FGRGB-101 in the list.
Perhaps that's the Problem?

**Comment by ronie-z-wave** [comment]
Forgot what I've said ... I've included the wrong device - could happen in test labor with more than one gateways ;) ... Now I can see 5-6 switchMultilevel classes generated by Fibaro RGBW ... I'll have a look at this

**Comment by Quax1507** [comment]
Same Problem in rc44

**Comment by ronie-z-wave** [comment]
Please have a look at my changes in 
https://github.com/Z-Wave-Me/home-automation/commit/c23c548dfffa3eff423d2dc50837dd307bcee0be

I did some improvements. Changing color should work now, also if the device is switched 'off'. 

Before the command 'off' has set it to (0,0,0) and with 'on' it was still (0,0,0) but 'on' ... only via changing the R/G/B device directly the color has changed, after that RGB device works again.

**Comment by Quax1507** [comment]
I can turn off and on but still no color change possible. Even no Output in log when changing color...
(Changing single colors outside the app works fine)

**Comment by ronie-z-wave** [comment]
Ok.  Your index.js of RGB looks like this now, right? 
https://github.com/Z-Wave-Me/home-automation/blob/develop/modules/RGB/index.js

In the RGB module I've added the following virtual devices produced by RGBW:
'Dimmer *-2 Fibar Group' to Red, 'Dimmer *-3 Fibar Group' to Green and 'Dimmer *-4 Fibar Group' to Blue ... ouput is a RGB LED +12V

After you have changed the index.js you need to restart z-way-server with command
'$sudo /etc/init.d/z-way-sever restart' ... maybe also you need to delete the active RGB instance and add it again.

**Comment by Quax1507** [comment]
Did all that. No success...
I can control device through single devices as above.

The RGBW created an RGB device on his own which also does not work. 
I have no idea.

**Comment by ronie-z-wave** [comment]
puh, what a tough nut ... all interviews in ExpertUI are successfull and you can see 6 dimmers + 3 energy meters, right?

If you check the browsers console and network traffic with a built-in developer tool (F12) does the RGB device send something after changing color or clicking on/off? It should send three commands - one to each integrated device.

Please add some screens of browsers console/network traffic and your elements view of smarthome ui maybe this will help.

**Comment by Quax1507** [comment]
In expert UI it is correct
![expert](https://cloud.githubusercontent.com/assets/12785318/8474376/f5d7eee6-20af-11e5-90cd-723c867170d4.PNG)

Swiching on in smarthome UI works
![switch on](https://cloud.githubusercontent.com/assets/12785318/8474400/1c16d11c-20b0-11e5-9050-9c02cf577075.PNG)

When changin Color, there is nothing logged in developer tool!

**Comment by ronie-z-wave** [comment]
hmm ok ... did you already clean your browsers cache? 
Try to open the palette, click into the color square and pull the curser to the right upper corner and release it ... also the other both scales will better react to this ...

If again nothing helps, please go for sure that:
---
- the whole RGB module is up to date (latest: https://github.com/Z-Wave-Me/home-automation/tree/develop/modules/RGB - sometimes there are problems with synchronizing if you are using tools like WinScp or FileZilla)
- if not: delete it from server and copy a fresh RGB module instead
- restart z-way-server
- delete old RGB instance
- add new RGB with correct devices for colors R/G/B
- clean browsers cache and reload elements view (F5)

RGB device behaviour:
---
on:
- if no color was adjusted before it sets each device (R/G/B) to 99% (255) - white light - otherwise it configures the latest color value (after server restart it is 255/255/255 again)

off:
- R/G/B to 0% (0)

change color:
- e.g. red - R 99% (255), G 0% (0), B 0% (0)
- click and pull to adjust color

I'm sure you did this already many times but if nothing helps sometimes it is better to start at the beginning again.

**Comment by Quax1507** [comment]
I tried all that and even tried again.
I also tried different browsers.
Unfortunatelly no success.

I also tried above commands - they work good!

Color picker does not produce any result and does not work...

Really strange!

**Comment by ronie-z-wave** [comment]
Ah ... I think the solution is near :dancers: 

Please try to overwrite /opt/z-way-server/htdocs/smarthome/ with latest dist from smarthome ui dev branch https://github.com/Z-Wave-Me/zwave-smarthome/tree/dev/dist ... after that refresh the page and try it again

It seems there is a ui problem too. With the old version (including 2.0.1) the color-picker is not loaded corectly. Now we have fixed this in next version. Sry for circumstances but I know this only since this morning.

**Comment by Quax1507** [comment]
Sound good. Will test it!
Can You tell me how to copy the whole branch onto my Raspi?
Sorry, no developer (yet) :-)

**Comment by ronie-z-wave** [comment]
No problem. Please go to https://github.com/Z-Wave-Me/zwave-smarthome/tree/dev and click on 'Download ZIP' at the right side. Unzip this file on your computer.

You need not to copy all stuff from this branch, the content of 'dist' folder should be enough. 
So make this folder '/opt/z-way-server/htdocs/smarthome/' on your raspi empty and upload the content from unzipped '/zwave-smarthome-dev/dist/' instead.

fyi: The /dist content is the minified version of /app and needs more less storage.

**Comment by Quax1507** [comment]
That did it! Thank You very much!

**Comment by ronie-z-wave** [comment]
No problem. You're welcome :)
