### ISSUE TITLE
Add duplicate button to app instance

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#212]
Create a new instance and add " (copy)" to the name and duplicate all params

**Comment by klaasjoerg** [comment]
Great. Since it probably takes a while, until this functionality appears:
Is it possible to simply cut & paste the params section properly from one scene to the other - without messing things up?  If yes, which would be the correct file to edit?
(Probably better shutting down zway before and after, right?)

**Comment by PoltoS** [comment]
config.json - add one more instance with changed id.

**Comment by ronie-z-wave** [comment]
@PoltoS: already on our todo list, unfortunately not done yet. I think it's worth to put this topic in the next minor release :)

**Comment by mh-zwave** [comment]
Since 2.3.6 you can clone/duplicate a app instance :)
![image](https://user-images.githubusercontent.com/20574625/48404791-57f6b580-e731-11e8-9645-a48101f1850d.png)
