### ISSUE TITLE
Widget not updated instantly

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#58]
Again! ;-(

The sceen shows that the UI log reported correct change, while graphics is not updated at all.

Pleeeeeaaaase fix it finally in all places!

![sonos onoff widget not updated](https://cloud.githubusercontent.com/assets/3664383/9982928/f369e252-5ff4-11e5-9267-6d2a7f62c0c8.png)

**Comment by aivs** [comment]
When I create widget (e.g. dummy device), on the panel it does not appear, but in console I see that new DummyDevice_76 updated.
Next, when I create widget (e.g. dummy device), I can't use in the rules, need to update the page.

**Comment by vades** [comment]
We heve tested it and graphic and buttons on/off are updated correctly.

**Comment by PoltoS** [comment]
1. @vades how about instantly adding devices on creation? Open two tabs and add in one of them the Dummy module. On the second the list of devices in Elements view is not updated.
2. @aivs requires more proof about on/off update - how to replicate?

**Comment by aivs** [comment]
Create Dummy Device and go to Widgets, where is Dummy ?
Need page reload.

**Comment by vades** [comment]
We can highlight new added device in  the elemt list. If list has many devices is  hard to find which devices is just installed. E.g:
On the top of elements show highlighet ssection "Just installed" with new elements.
1. How can front-endto recognize new installed device?

**Comment by ronie-z-wave** [comment]
@PoltoS @aivs : Thought, thats a cache problem, but seems not.

@PoltoS : Why isn't device creation recognized via /devices?since=* ? Ok, it is. Device is there but structureChange is false - should be true... think that will solve the problem.

@vades : Good question. Maybe via adding a flag if virtual device has been created and removing it after 5min? Or by comparing old devices.json with new one? Problem is, that devices are also created by re-/starting Z-Wave App ...

@PoltoS : Hmm On/Off issue is strange, because Sonos is using normal switchBinary widget and this works in our tests with other widgets of same type - unfortunately we aren't able to test with Sonos ... only if there is no feedback from device (the screen doesn't look so) the level stays as it is ... But command is send correctly to Sonos device? What about devices since? has it changed correctly? Maybe its a similar Problem with this like adding devices?

**Comment by aivs** [comment]
The new widget should appear at the end of the list, not in random place.

**Comment by ronie-z-wave** [comment]
Issue still there in latest versions?

**Comment by vades** [comment]
The new installed element has green border (for 24 hours)
