### ISSUE TITLE
Aeon Multi Sensor Gen5 does not show the percent signs for humidity

### ISSUE THREAD

**Issue by j1k1** [Z-Wave-Me/zwave-smarthome#68]
Aeon Multi Sensor Gen5 does not show the percent signs for humidity sh ui but shows it correct in expert ui.
![expertui](https://cloud.githubusercontent.com/assets/12872453/10708974/1db3b76c-7a1d-11e5-8efd-ecc87f495955.png)
![smarthomeui](https://cloud.githubusercontent.com/assets/12872453/10708973/1daf1e28-7a1d-11e5-95ea-5f549ee89493.png)

UI version: 1.0.1

**Comment by aivs** [comment]
I think this ia a zway problem, not ui.
Same issues:
https://github.com/Z-Wave-Me/z-way-issues/issues/67

**Comment by j1k1** [comment]
But the character is displayed in the expert user interface. Why is that?

**Comment by PoltoS** [comment]
Please show /ZAutomation/api/v1/devices/XXXXXX for this device (change XXXX to fit your device).

**Comment by j1k1** [comment]
{"data":{"creatorId":1,"deviceType":"sensorBinary","h":-315411077,"hasHistory":false,"id":"ZWayVDev_zway_6-0-48-1","location":6,"metrics":{"probeTitle":"General purpose","scaleTitle":"","icon":"motion","level":"off","title":"Ute - Entre multisensor"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1445681091},"code":200,"message":"200 OK","error":null}

**Comment by PoltoS** [comment]
Z-Way version? looks old

**Comment by PoltoS** [comment]
may be stop Z-Way, remove from config.json-xxxx this device (part of JS object) and start again, may be Z-Way will generate it correctly?

**Comment by PoltoS** [comment]
and /ZWaveAPI/Run/devices[6].SensorMultilevel.data[5] ?

**Comment by j1k1** [comment]
{"invalidateTime":1438023624,"updateTime":1445690256,"type":"empty","value":null,"sensorTypeString":{"invalidateTime":1435985794,"updateTime":1435985795,"type":"string","value":"Humidity"},"val":{"invalidateTime":1435985794,"updateTime":1445690256,"type":"float","value":73},"deviceScale":{"invalidateTime":1435985794,"updateTime":1445690256,"type":"int","value":0},"scale":{"invalidateTime":1435985794,"updateTime":1445690256,"type":"int","value":0},"scaleString":{"invalidateTime":1435985794,"updateTime":1445690256,"type":"string","value":"%"}}

**Comment by christianpaetz** [comment]
I investigated the problem. Its more or lts a race problem. the Z-Wave Module renders the Ui element based on Interview data and here the information about the scale sometimes comes too late, hence the scale field in SmartHme UI data is "null". The correct scale comes later with ML Sensor reports but this does not overwrite the scale value in smarthome UI anymore, only in Expert UI because Expert Ui takes data right out of zway object. I asked Niels to make a little change. Every ML Sensor report updates the scale ID for smarthome UI elements too. 
The problem comes up in devices with a lot ML Sensor IDs, like Aeonlabs or ZWeather

**Comment by ronie-z-wave** [comment]
Should be solved with next version.
